// this file was generated by serverless-auto-swagger
module.exports = {
  swagger: '2.0',
  info: {
    title: 'Product store',
    version: '1',
  },
  paths: {
    '/products/{productId}': {
      get: {
        summary: 'getProductsById',
        description: '',
        operationId: 'getProductsById.get.products/{productId}',
        consumes: ['application/json'],
        produces: ['application/json'],
        parameters: [
          {
            name: 'productId',
            in: 'path',
            required: true,
            type: 'string',
          },
        ],
        responses: {
          200: {
            description: 'Successfull response for product',
            schema: {
              $ref: '#/definitions/Product',
            },
          },
          400: {
            description: 'Bad request: productId is required',
          },
          404: {
            description: 'Product is not found',
          },
          500: {
            description: 'Internal server error',
          },
        },
      },
    },
    '/products': {
      get: {
        summary: 'getProductsList',
        description: '',
        operationId: 'getProductsList.get.products',
        consumes: ['application/json'],
        produces: ['application/json'],
        parameters: [],
        responses: {
          200: {
            description: 'Successfull response for products',
            schema: {
              $ref: '#/definitions/Products',
            },
          },
          500: {
            description: 'Internal server error',
          },
        },
      },
      post: {
        summary: 'createProduct',
        description: '',
        operationId: 'createProduct.post.products',
        consumes: ['application/json'],
        produces: ['application/json'],
        parameters: [],
        responses: {
          201: {
            description: 'Product successfully created',
            schema: {
              $ref: '#/definitions/Products',
            },
          },
          400: {
            description: 'Bad request',
          },
          500: {
            description: 'Internal server error',
          },
        },
      },
    },
  },
  definitions: {
    Product: {
      properties: {
        count: {
          title: 'Product.count',
          type: 'number',
        },
        description: {
          title: 'Product.description',
          type: 'string',
        },
        id: {
          title: 'Product.id',
          type: 'string',
        },
        price: {
          title: 'Product.price',
          type: 'number',
        },
        title: {
          title: 'Product.title',
          type: 'string',
        },
      },
      required: ['count', 'description', 'id', 'price', 'title'],
      additionalProperties: false,
      title: 'Product',
      type: 'object',
    },
    Products: {
      items: {
        $ref: '#/definitions/Product',
      },
      title: 'Products',
      type: 'array',
    },
  },
  securityDefinitions: {},
  basePath: '/dev',
  host: 'os1u2n4md2.execute-api.ap-south-1.amazonaws.com',
  schemes: ['https'],
};
