# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'
plugins:
  - serverless-dotenv-plugin
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

  # you can overwrite defaults here
  stage: '${opt:stage, "dev"}'
  region: ap-south-1

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    PGHOST: ${env:PGHOST}
    PGUSER: ${env:PGUSER}
    PGDATABASE: ${env:PGDATABASE}
    PGPASSWORD: ${env:PGPASSWORD}
    PGPORT: ${env:PGPORT}
    REGION: '${self:provider.region}'
    SNS_CREATE_PRODUCT_TOPIC_ARN:
      Ref: createProductTopic1

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action: 'sns:*'
          Resource:
            Ref: createProductTopic1

resources:
  Resources:
    catalogItemsQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'sqs-queue-${self:provider.stage}-catalogItemsQueue'
    createProductTopic1:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic1
    createProductTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Ref: 'createProductTopic1'
        Protocol: 'email'
        Endpoint: '${env:EMAIL_ADDRESS1}'
        FilterPolicy:
          price:
            - numeric: ['<', 1000]
    createProductTopicFilteredSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${env:EMAIL_ADDRESS2}
        Protocol: email
        TopicArn:
          Ref: 'createProductTopic1'
        FilterPolicy:
          price:
            - numeric: ['>=', 1000]
  Outputs:
    catalogItemsQueueUrl:
      Description: 'SQS URL'
      Value:
        Ref: 'catalogItemsQueue'
      Export:
        Name: 'catalogItemsQueueUrl-${opt:stage, self:provider.stage}'

    catalogItemsQueueArn:
      Description: 'SQS Arn value'
      Value:
        Fn::GetAtt: [catalogItemsQueue, Arn]
      Export:
        Name: 'catalogItemsQueueArn-${opt:stage, self:provider.stage}'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  currentStage: '${opt:stage, self:provider.stage}'
  autoswagger:
    title: 'Product store'
    apiType: 'http'
    typefiles: ['src/types/product.ts']
    generateSwaggerOnDeploy: true
    swaggerPath: 'swagger'
    basePath: '/${self:provider.stage}'
    host: '8ui2filzzh.execute-api.ap-south-1.amazonaws.com'
    schemes: ['https']

# you can add packaging information here
package:
  individually: true
  exclude:
    - ./**

functions:
  getProductsById:
    handler: src/functions/getProductsById/handler.default
    package:
      patterns:
        - 'src/functions/getProductsById/**'
    events:
      - http:
          path: products/{productId}
          method: GET
          cors: true
          responseData:
            {
              200: { description: 'Successfull response for product', bodyType: Product },
              400: { description: 'Bad request: productId is required' },
              404: { description: 'Product is not found' },
              500: { description: 'Internal server error' },
            }

  getProductsList:
    handler: src/functions/getProductsList/handler.default
    package:
      patterns:
        - 'src/functions/getProductsList/**'
    events:
      - http:
          path: products
          method: GET
          cors: true
          responseData:
            {
              200: { description: 'Successfull response for products', bodyType: Products },
              500: { description: 'Internal server error' },
            }
  createProduct:
    handler: src/functions/createProduct/handler.default
    package:
      patterns:
        - 'src/functions/createProduct/**'
    events:
      - http:
          path: products
          method: POST
          cors: true
          bodyType: PartialProduct
          responseData:
            {
              201: { description: 'Product successfully created', bodyType: Products },
              400: { description: 'Bad request' },
              500: { description: 'Internal server error' },
            }
  catalogBatchProcess:
    handler: src/functions/catalogBatchProcess/handler.default
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt: ['catalogItemsQueue', 'Arn']
          maximumBatchingWindow: 60
